name: Format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Check formatting
        run: |
          pnpm fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Code is not properly formatted. Please run 'pnpm fmt:fix' to fix formatting."
            echo "Files that need formatting:"
            git status --porcelain
            exit 1
          else
            echo "✅ All files are properly formatted!"
          fi 