# .github/workflows/preview-commit.yml

name: Preview Commit

on:
  push:
    branches-ignore:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git as Taeyang
        run: |
          git config user.name "Corey Mostero"
          git config user.email "coreymostero@gmail.com"

      - name: Create preview commit
        run: |
          git commit --allow-empty -m "preview commit"

      - name: Push preview commit
        env:
          GH_TOKEN: ${{ secrets.TAEYANG_PAT }}
        run: |
          git push https://taeyangcode:${GH_TOKEN}@github.com/calhacks/honey-pot.git HEAD
